### ISSUE TITLE
PHP 8.1 Enum support

### ISSUE THREAD

**Issue by roquie** [cycle/orm#230]
If PHP version >= 8.1 enable enum support for entity fields.

**Comment by sergey-telpuk** [comment]
@roxblnfk Hi, This question is actual now. Can cycle 2.0 support `enum`?

**Comment by roxblnfk** [comment]
We didn't work on this task yet

**Comment by roxblnfk** [comment]
I wrote some test about PHP 8.1 Enum:

https://github.com/cycle/orm/blob/142db533822ea24d6b53c2ee298aea2dbd2f425d/tests/ORM/Functional/Driver/Common/Enum/EnumTest.php

The DBAL package can not store Emun value because it trying to cast Enum value to string.

Solutions:

 - We can fix it to handle it in the DBAL but we doesn't know what we have to save: enum name or enum value.
 - Also we can do supporting for `enum` rule by the default Typecast handler and convert a Enum value to scalar (int/string) using Enum::value method.

**Comment by sergey-telpuk** [comment]
@roxblnfk Hi, how about Typecast_handler? if I'm not mistaken, we can add cast and uncast for variety of types

**Comment by roxblnfk** [comment]
> @roxblnfk Hi, how about Typecast_handler? if I'm not mistaken, we can add cast and uncast for variety of types

Yes, i wrote about it in the second option. We can add rule `enum`.

**Comment by chatii** [comment]
I tried enum type-casting, Seems to be working fine.

Enum
```php
<?php
declare(strict_types=1);

namespace App\Enum;

use Cycle\Database\Injection\ValueInterface;

enum StatusEnum: int implements ValueInterface
{
    case NotYet = 0;
    case Submitted = 1;

    public static function typecast(int $value): self
    {
        return self::from($value);
    }

    public function rawValue(): string
    {
        return (string)$this->value;
    }

    public function rawType(): int
    {
        return \PDO::PARAM_INT;
    }
}

```

Entity
```php
// ...
    public function __construct(
        // ...
        #[Column(type: "integer", typecast: StatusEnum::class)]
        private StatusEnum $status,
        // ...
    ) {
    }
// ...
```

**Comment by roxblnfk** [comment]
Release: https://github.com/cycle/orm/releases/tag/v2.2.0
Documentation: https://cycle-orm.dev/docs/advanced-column-wrappers/2.x/en#enum-typecast
