### ISSUE TITLE
Unable to resolve relation target for single table entities

### ISSUE THREAD

**Issue by myavchik** [cycle/orm#29]
run cycle:sync and got:

[Cycle\Schema\Exception\RelationException]
Unable to resolve `last`.`info` relation target (not found or invalid)

Entities example:

```
/** @Entity */
class Post 
{
    /** @Column(type="primary") */
    public $id;
}

/** @Entity */
class Article extends Post
{
    /** @Column(type="string") */
    public $articleTitle;
}

/** @Entity */
class Last
{
    /** @HasOne(target="Article") */
    public $info;
}
```

**Comment by wolfy-j** [comment]
Hi, this is "kinda" the correct behavior. Since the child is always stored in the parent table the relation
`info` will be pointing to `Post` as well. So we have 2 options:
1) Change the `info` target to `Post`
2) We can automatically point it to `Post` since we know the parent (a.k.a add sugar)

I think the second is preferred. What do you think?

**Comment by wolfy-j** [comment]
Patch is on it's way.

**Comment by wolfy-j** [comment]
The issue of aliasing to STI has been addressed in https://github.com/cycle/annotated/releases/tag/v2.0.1 Please update.

**Comment by myavchik** [comment]
Now it's working, thank you.
