### ISSUE TITLE
[Cycle 2.0] Final entity class

### ISSUE THREAD

**Issue by sergey-telpuk** [cycle/orm#303]
Hi, Why can I make like `final class` entity?

**Comment by butschster** [comment]
As I understand. You want to ask about the reason you can not use final class in your entities?

**Comment by sergey-telpuk** [comment]
Sorry, my bad, yes I have final entities but cycle can't map them because they are final

**Comment by butschster** [comment]
> Sorry, my bad, yes I have final entities but cycle can't map them because they are final

Yeah, it's all because of [proxy mapper](https://cycle-orm.dev/docs/mapper-proxy-mapper/2.x/en) used by default in CycleORM.

Without proxy entities you can't use relations. If you don't use relations use alternate mapper, for example [promise mapper](https://cycle-orm.dev/docs/mapper-promise-mapper/2.x/en)

**Comment by sergey-telpuk** [comment]
I think, It's the strict rule that should be described in doc. In my point of view, the final class should impact on our logic

**Comment by roxblnfk** [comment]
> I think, It's the strict rule that should be described in doc. In my point of view, the final class should impact on our logic

See the `limitations` section in the proxy-maper documentation

https://cycle-orm.dev/docs/mapper-proxy-mapper/2.x/en#limitations
